# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.7

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /home/software/clion-2017.1/bin/cmake/bin/cmake

# The command to remove a file.
RM = /home/software/clion-2017.1/bin/cmake/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/program/fnotify

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/program/fnotify/cmake-build-debug

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/home/software/clion-2017.1/bin/cmake/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/home/software/clion-2017.1/bin/cmake/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/program/fnotify/cmake-build-debug/CMakeFiles /home/program/fnotify/cmake-build-debug/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/program/fnotify/cmake-build-debug/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named fnotify

# Build rule for target.
fnotify: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 fnotify
.PHONY : fnotify

# fast build rule for target.
fnotify/fast:
	$(MAKE) -f CMakeFiles/fnotify.dir/build.make CMakeFiles/fnotify.dir/build
.PHONY : fnotify/fast

config.o: config.c.o

.PHONY : config.o

# target to build an object file
config.c.o:
	$(MAKE) -f CMakeFiles/fnotify.dir/build.make CMakeFiles/fnotify.dir/config.c.o
.PHONY : config.c.o

config.i: config.c.i

.PHONY : config.i

# target to preprocess a source file
config.c.i:
	$(MAKE) -f CMakeFiles/fnotify.dir/build.make CMakeFiles/fnotify.dir/config.c.i
.PHONY : config.c.i

config.s: config.c.s

.PHONY : config.s

# target to generate assembly for a file
config.c.s:
	$(MAKE) -f CMakeFiles/fnotify.dir/build.make CMakeFiles/fnotify.dir/config.c.s
.PHONY : config.c.s

fnotify.o: fnotify.c.o

.PHONY : fnotify.o

# target to build an object file
fnotify.c.o:
	$(MAKE) -f CMakeFiles/fnotify.dir/build.make CMakeFiles/fnotify.dir/fnotify.c.o
.PHONY : fnotify.c.o

fnotify.i: fnotify.c.i

.PHONY : fnotify.i

# target to preprocess a source file
fnotify.c.i:
	$(MAKE) -f CMakeFiles/fnotify.dir/build.make CMakeFiles/fnotify.dir/fnotify.c.i
.PHONY : fnotify.c.i

fnotify.s: fnotify.c.s

.PHONY : fnotify.s

# target to generate assembly for a file
fnotify.c.s:
	$(MAKE) -f CMakeFiles/fnotify.dir/build.make CMakeFiles/fnotify.dir/fnotify.c.s
.PHONY : fnotify.c.s

notify.o: notify.c.o

.PHONY : notify.o

# target to build an object file
notify.c.o:
	$(MAKE) -f CMakeFiles/fnotify.dir/build.make CMakeFiles/fnotify.dir/notify.c.o
.PHONY : notify.c.o

notify.i: notify.c.i

.PHONY : notify.i

# target to preprocess a source file
notify.c.i:
	$(MAKE) -f CMakeFiles/fnotify.dir/build.make CMakeFiles/fnotify.dir/notify.c.i
.PHONY : notify.c.i

notify.s: notify.c.s

.PHONY : notify.s

# target to generate assembly for a file
notify.c.s:
	$(MAKE) -f CMakeFiles/fnotify.dir/build.make CMakeFiles/fnotify.dir/notify.c.s
.PHONY : notify.c.s

watch.o: watch.c.o

.PHONY : watch.o

# target to build an object file
watch.c.o:
	$(MAKE) -f CMakeFiles/fnotify.dir/build.make CMakeFiles/fnotify.dir/watch.c.o
.PHONY : watch.c.o

watch.i: watch.c.i

.PHONY : watch.i

# target to preprocess a source file
watch.c.i:
	$(MAKE) -f CMakeFiles/fnotify.dir/build.make CMakeFiles/fnotify.dir/watch.c.i
.PHONY : watch.c.i

watch.s: watch.c.s

.PHONY : watch.s

# target to generate assembly for a file
watch.c.s:
	$(MAKE) -f CMakeFiles/fnotify.dir/build.make CMakeFiles/fnotify.dir/watch.c.s
.PHONY : watch.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... fnotify"
	@echo "... config.o"
	@echo "... config.i"
	@echo "... config.s"
	@echo "... fnotify.o"
	@echo "... fnotify.i"
	@echo "... fnotify.s"
	@echo "... notify.o"
	@echo "... notify.i"
	@echo "... notify.s"
	@echo "... watch.o"
	@echo "... watch.i"
	@echo "... watch.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

